sonar.projectKey=mentorhub
sonar.projectName=MentorHub
sonar.projectVersion=1.0

sonar.sources=apps/web/src,apps/server/src
sonar.tests=apps/web/src,apps/server/src
sonar.test.inclusions=**/*.spec.ts,**/*.spec.tsx

sonar.exclusions=**/node_modules/**,**/dist/**,**/src/generated/**,**/*.d.ts
sonar.coverage.exclusions=**/node_modules/**,**/*.spec.ts,**/*.spec.tsx
