services:
  db:
    image: postgres:15
    container_name: final_project_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: final_project
      POSTGRES_PASSWORD: Abuchi123
      POSTGRES_DB: final_project
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
